#!/usr/bin/env bash

GU=$(which gu)

if [[ -z $GU ]]; then
  echo "ERROR: Can't find gu."
  exit 1
fi

GRAALVM_HOME=$(dirname $(dirname $(dirname $(dirname $(readlink -f $GU)))))

if [[ -f $GRAALVM_HOME/bin/native-image ]]; then
  $GRAALVM_HOME/bin/native-image $@
else
  echo "ERROR: native-image is not installed yet: run 'gu install native-image'"
fi

