#!/usr/bin/env bash

GRAALVM_HOME=$(dirname $(dirname $(readlink -f $0)))

if [[ -f $GRAALVM_HOME/languages/nodejs/bin/node ]]; then
  $GRAALVM_HOME/languages/nodejs/bin/node $@
else
  echo "ERROR: nodejs runtime is not installed yet: run 'gu install nodejs'"
fi

