#!/usr/bin/env bash

GRAALVM_HOME=$(dirname $(dirname $(readlink -f $0)))
LLVM_TOOLCHAIN=$($GRAALVM_HOME/bin/lli --print-toolchain-path)

if [[ -f $LLVM_TOOLCHAIN/clang++ ]]; then
  $LLVM_TOOLCHAIN/clang++ $@
else
  echo "ERROR: llvm toolchain is not installed yet: run 'gu install llvm-toolchain'"
fi

