#!/usr/bin/env bash

GRAALVM_HOME=$(dirname $(dirname $(readlink -f $0)))

if [[ -f $GRAALVM_HOME/languages/R/bin/R ]]; then
  $GRAALVM_HOME/languages/R/bin/R $@
else
  echo "ERROR: r runtime is not installed yet: run 'gu install r'"
fi

