#!/usr/bin/env bash

GRAALVM_HOME=$(dirname $(dirname $(readlink -f $0)))

if [[ -f $GRAALVM_HOME/bin/native-image ]]; then
  $GRAALVM_HOME/bin/native-image $@
else
  echo "ERROR: native-image is not installed yet: run 'gu install native-image'"
fi

