#!/usr/bin/env bash

GU=$(which gu)

if [[ -z $GU ]]; then
  echo "ERROR: Can't find gu."
  exit 1
fi

GRAALVM_HOME=$(dirname $(dirname $(dirname $(dirname $(readlink -f $GU)))))

if [[ -f $GRAALVM_HOME/languages/R/bin/R ]]; then
  $GRAALVM_HOME/languages/R/bin/R $@
else
  echo "ERROR: r runtime is not installed yet: run 'gu install r'"
fi

