#!/usr/bin/env bash

GU=$(which gu)

if [[ -z $GU ]]; then
  echo "ERROR: Can't find gu."
  exit 1
fi

GRAALVM_HOME=$(dirname $(dirname $(dirname $(dirname $(readlink -f $GU)))))

if [[ -f $GRAALVM_HOME/languages/nodejs/bin/node ]]; then
  $GRAALVM_HOME/languages/nodejs/bin/node $@
else
  echo "ERROR: nodejs runtime is not installed yet: run 'gu install nodejs'"
fi

