#!/usr/bin/env bash

GRAALVM_HOME=$(dirname $(dirname $(readlink -f $0)))

if [[ -f $GRAALVM_HOME/languages/python/bin/graalpython ]]; then
  $GRAALVM_HOME/languages/python/bin/graalpython $@
else
  echo "ERROR: python runtime is not installed yet: run 'gu install python'"
fi

